include:
  - linux-desktop.discord
  - linux-desktop.dropbox
  - linux-desktop.emojione
  - linux-desktop.environments
  - linux-desktop.google-chrome
  - linux-desktop.init
  - linux-desktop.mattermost
  - linux-desktop.numix
  - linux-desktop.spotify
  - linux-desktop.slack
  - linux-desktop.steam
  - linux-desktop.veracrypt
  - linux-desktop.virtualbox
  - linux-desktop.vs-code
  - linux-desktop.xfce
