# HTTP -> HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# LetsEncrypt wildcard domains
[acme]
email = "{{ letsencrypt['email'] }}"
storage = "acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0

{% for domain in letsencrypt.get('domains', []) %}
[[acme.domains]]
  main = "{{ domain }}"
{% endfor %}
